apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: spinifex-embedding-pipeline
  annotations:
    scenarios.ai.sap.com/name: "Embeddings"
    scenarios.ai.sap.com/description: "Embedding pipeline"
    executables.ai.sap.com/name: "Embedding Executable"
    executables.ai.sap.com/description: "Calls SAP embedding model"
  labels:
    scenarios.ai.sap.com/id: "spinifex"
    ai.sap.com/version: "1.0"
spec:
  imagePullSecrets:
    - name: spinifexdr
  entrypoint: main
  templates:
    - name: main
      container:
        image: docker.io/wrodrigueze/spinifexdr:latest
        command: ["python", "embedding_caller.py"]
        env:
          - name: SAP_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: sap-secrets
                key: client_id
          - name: SAP_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: sap-secrets
                key: client_secret
          - name: SAP_AUTH_URL
            valueFrom:
              secretKeyRef:
                name: sap-secrets
                key: auth_url
