apiVersion: ai.sap.com/v1alpha1
kind: WorkflowTemplate
metadata:
  name: spinifex-embedding-pipeline
spec:
  entrypoint: main
  templates:
    - name: main
      container:
        image: wrodrigueze/spinifexdr:latest
        command: ["python", "embedding_caller.py"]
        env:
          - name: SAP_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: sap-secrets
                key: client_id
          - name: SAP_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: sap-secrets
                key: client_secret
          - name: SAP_AUTH_URL
            valueFrom:
              secretKeyRef:
                name: sap-secrets
                key: auth_url
